security:
  oauth2:
    client:
      clientId: 338892837563-3r31fl26bl9erk5eraruc2f5fsh9vecf.apps.googleusercontent.com
      clientSecret: K7WK8gEgQWQgz2KYoX5hju0X
      accessTokenUri: https://oauth2.googleapis.com/token
      scope: "profile,openid,email"
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.springframework.security: DEBUG