security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 932377803533-gdl0j40iijtek6cc797sk0eap8ggmo36.apps.googleusercontent.com
      clientSecret: 9bYO45M6SRLNSDuJXwBXigFn
      accessTokenUri: https://oauth2.googleapis.com/token
      scope: "profile,openid,email"
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
#      csrf-enabled: false
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

spring:
  devtools:
    add-properties: false

  jpa:
    hibernate:
      ddl-auto: update

    database: POSTGRESQL

  logging:
  level:
    org.springframework.security: DEBUG

### PostgreSQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library-app
    username:
    password:

  level:
    org:
      hibernate:
        SQL: DEBUG

        type:
          descriptor:
            sql:
              BasicBinder: TRACE

